sudo: required 
dist: bionic 
language: generic 
compiler:
  - gcc
env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - BEFORE_SCRIPT='cd /root/catkin_ws/src/soccer_ws/external/darknet_ros & touch darknet_ros/CATKIN_IGNORE & touch darknet_ros_msgs/CATKIN_IGNORE'

  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
- source .ci_config/travis.sh
