sudo: required 
dist: bionic 
language: generic 
compiler:
  - gcc
env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - BEFORE_SCRIPT="catkin config --blacklist darknet_ros"
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
- source .ci_config/travis.sh
