sudo: required 
dist: bionic 
language: generic 
compiler:
  - gcc
env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
before_script:
  - touch $HOME/catkin_ws/src/soccer_ws/external/CATKIN_IGNORE
script: 
- source .ci_config/travis.sh
