# matrix:
#  include:
#    # works on Precise and Trusty
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-8
#      env:
#        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && CXX_FOR_BUILD=g++-8 && CC_FOR_BUILD=gcc-8 && TRAVIS_COMPILER=g++-8"

language: cpp

#before_install:
#  - eval "${MATRIX_EVAL}"

before_script:
  - dpkg -l
  - ls /usr/
  - ls /usr/local/
  - ls /usr/bin/
  # install GCC ARM from GNU ARM Embedded Toolchain PPA
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-arm-embedded

  # build GNU Make 4.1 from source
  - wget http://ftp.gnu.org/gnu/make/make-4.1.tar.gz
  - tar xvf make-4.1.tar.gz
  - cd make-4.1
  - ./configure
  - make -j16
  - sudo make install
  - cd ..
  - rm -rf make-4.1

  # add Make to path
  - export PATH=/usr/local/bin/:$PATH

  - wget https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz
  - tar xf gcc-8.2.0.tar.xz
  - cd gcc-8.2.0
  - ./contrib/download_prerequisites
  - mkdir build && cd build
  - ../configure --prefix=/usr --disable-multilib --disable-libmpx --with-system-zlib --enable-languages=c,c++,fortran,go,objc,obj-c++ && make -j16

script:
  - ls /usr/bin/
  - sudo ln -s /usr/bin/gcc-8.2 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8.2 /usr/local/bin/g++
  #- sudo apt-get install gcc-8-multilib g++-8-multilib
  - g++ -v
  - cd $TRAVIS_BUILD_DIR/Robot/
  - make -j12 TARGET=F4 all
  - make -j12 TARGET=F7 all
