version: "3.3"

x-soccerbot: &soccerbot
  image: utrarobosoccer/soccerbot
  build:
    context: .
  network_mode: host
  deploy:
    resources:
      limits:
        cpus: '4'
        memory: 16384MB
  command: /bin/bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch soccerbot soccerbot.launch __ns:=$$ROBOT_NAME || sleep infinity"
  environment:
    ROBOCUP_MIRROR_SERVER_IP: locahost:3737
    ROBOCUP_GAMECONTROLLER_IP: 127.0.1.1:3939
    ROBOCUP_TEAM_PLAYER1_IP: localhost
    ROBOCUP_TEAM_PLAYER2_IP: localhost
    ROBOCUP_TEAM_PLAYER3_IP: localhost
    ROBOCUP_TEAM_PLAYER4_IP: localhost

services:
  friendly1: # Goalie
    <<: *soccerbot
    environment:
      X_POS: 0.0
      Y_POS: -3.5
      ANGLE: 1.57
      GOALIE: "true"
      ROBOCUP_ROBOT_ID: 1
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10001
      ROBOT_NAME: robot1
      COMPETITION: "true"
#  friendly2: # Left midfield
#    <<: *soccerbot
#    environment:
#      X_POS: -1.5
#      Y_POS: -1.5
#      ANGLE: 1.57
#      ROBOCUP_ROBOT_ID: 2
#      ROBOCUP_TEAM_COLOR: "red"
#      ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10002
#      ROBOT_NAME: robot2

#  friendly3: # Right midfield
#    <<: *soccerbot
#    environment:
#      X_POS: 1.5
#      Y_POS: -1.5
#      ANGLE: 1.57
#      ROBOCUP_ROBOT_ID: 3
#      ROBOCUP_TEAM_COLOR: "red"
#      ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10003
#      ROBOT_NAME: robot3

#  friendly4: # Striker
#    <<: *soccerbot
#    environment:
#      X_POS: 0.0
#      Y_POS: -0.8
#      ANGLE: 1.57
#      ROBOCUP_ROBOT_ID: 4
#      ROBOCUP_TEAM_COLOR: "red"
#      ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10004
#      ROBOT_NAME: robot4

  oppponent1: # Goalie
    <<: *soccerbot
    environment:
      X_POS: 0.0
      Y_POS: 3.5
      ANGLE: -1.57
      GOALIE: "true"
      ROBOCUP_ROBOT_ID: 1
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: localhost:10021
      ROBOT_NAME: opponent1

#  oppponent2: # Left midfield
#    <<: *soccerbot
#    environment:
#      X_POS: -1.5
#      Y_POS: 1.5
#      ANGLE: -1.57
#      ROBOCUP_ROBOT_ID: 2
#      ROBOCUP_TEAM_COLOR: "blue"
#      ROBOCUP_SIMULATOR_ADDR: localhost:10022
#      ROBOT_NAME: opponent2

#  oppponent3: # Right midfield
#    <<: *soccerbot
#    environment:
#      X_POS: 1.5
#      Y_POS: 1.5
#      ANGLE: -1.57
#      ROBOCUP_ROBOT_ID: 3
#      ROBOCUP_TEAM_COLOR: "blue"
#      ROBOCUP_SIMULATOR_ADDR: localhost:10023
#      ROBOT_NAME: opponent3

#  oppponent4: # striker
#    <<: *soccerbot
#    environment:
#      X_POS: 0.0
#      Y_POS: 0.8
#      ANGLE: -1.57
#      ROBOCUP_ROBOT_ID: 4
#      ROBOCUP_TEAM_COLOR: "blue"
#      ROBOCUP_SIMULATOR_ADDR: localhost:10024
#      ROBOT_NAME: opponent4
