version: "3.3"

# Setup instructions
# --------------------
# Install docker (https://docs.docker.com/engine/install/ubuntu/)
# sudo apt-get remove docker docker-engine docker.io containerd runc
# sudo apt-get update sudo apt-get install ca-certificates curl gnupg lsb-release
# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# sudo apt-get update
# sudo apt-get install docker-ce docker-ce-cli containerd.io

# Install docker-compose (https://docs.docker.com/compose/install/)
# sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose
# sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
# sudo groupadd docker
# sudo usermod -aG docker $USER
# Log in and log back out

# Install docker-compose NVIDIA tools
# curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | sudo apt-key add -
# distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
# curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
# sudo apt-get update
# sudo apt-get install -y nvidia-container-runtime nvidia-container-toolkit mesa-utils
# sudo systemctl restart docker
# echo "xhost +local:docker" >> ~/.bashrc && source ~/.bashrc

# Running Instructions
# --------------------
# docker-compose build or docker-compose pull
# docker-compose up

# Note: To run just simulator run docker-compose up simulator
# Note: You never need to build the images a second time as all the code is mounted
# Note: To run the full game run docker-compose -f docker-compose.full.yaml up

# Tips and tricks
# --------------------
# docker ps - list all of the docker containers that are running
# docker image ls - list all of the docker images that are built
# docker rm $(docker ps -aq) - Remove all not running docker containers
# docker stop $(docker ps -aq) - Stop all not running docker containers
# docker system prune --all - Delete all docker images
# docker exec -it <docker image id> bash - SSH into a docker image to see whats going on inside it

# docker-compose build - Build all docker images
# docker-compose pull - Takes images from dockerhub
# docker-compose push - Push all docker
# docker-compose up - Start the containers specified in this file

x-soccerbot: &soccerbot
  image: utrarobosoccer/soccerbot
  privileged: true
  build:
    context: .
    target: builder
#  network_mode: host
  cap_add:
    - SYS_PTRACE
  pid: "host"
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu, compute, utility, graphics ]
  command: /bin/bash -c "export ROS_MASTER_URI=http://$$(hostname -i):11311 && export ROS_IP=$$(hostname -i) &&
    source ~/catkin_ws/devel/setup.bash &&
    roslaunch soccerbot soccerbot.launch __ns:=robot$$ROBOCUP_ROBOT_ID || sleep infinity;"
  volumes:
    - .:/root/catkin_ws/src/soccerbot
      #    - /home/${USER}/catkin_ws/:/root/catkin_ws/
      #    - /home/${USER}/catkin_ws/:/home/${USER}/catkin_ws/
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw
    - /dev/snd:/dev/snd:rw

services:

  simulator:
    image: utrarobosoccer/webots
    privileged: true
    build:
      context: external
    cap_add:
      - SYS_PTRACE
    pid: "host"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu, compute, utility, graphics]
    command: bash -c "cd webots && ./webots --batch --sysinfo --log-performance=performance.log --no-sandbox ./projects/samples/contests/robocup/worlds/robocup.wbt"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
      - /dev/snd:/dev/snd:rw
      - ./external/webots/projects/samples/contests/robocup/worlds:/usr/local/webots/projects/samples/contests/robocup/worlds:rw
      - ./external/webots/projects/samples/contests/robocup/controllers/referee/referee.py:/usr/local/webots/projects/samples/contests/robocup/controllers/referee/referee.py:rw
      - ./external/webots/projects/samples/contests/robocup/controllers/referee/udp_bouncer.py:/usr/local/webots/projects/samples/contests/robocup/controllers/referee/udp_bouncer.py:rw
      - ./external/webots/projects/samples/contests/robocup/controllers/referee/game.json:/usr/local/webots/projects/samples/contests/robocup/controllers/referee/game.json:rw
      - ./external/webots/projects/samples/contests/robocup/controllers/referee/team_1_single.json:/usr/local/webots/projects/samples/contests/robocup/controllers/referee/team_1.json:rw
      - ./external/webots/projects/samples/contests/robocup/controllers/referee/team_2_single.json:/usr/local/webots/projects/samples/contests/robocup/controllers/referee/team_2.json:rw
      - ./external/webots/projects/samples/contests/robocup/protos/:/usr/local/webots/projects/samples/contests/robocup/protos/:rw
    environment:
      DISPLAY: unix$DISPLAY
      JAVA_HOME: /usr
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR

  friendly:
    <<: *soccerbot
    ports:
      - 11311:11311
    environment:
      X_POS: 2
      Y_POS: -3.14
      YAW: 1.57
      ROBOCUP_ROBOT_ID: 1
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10001"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      ROBOCUP_TEAM_ID: 16
      ENABLE_PYBULLET: "false"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1

  opponent:
    <<: *soccerbot
    ports:
      - 11312:11311
    environment:
      ROS_MASTER: "true"
      X_POS: -2
      Y_POS: -3.14
      YAW: 1.57
      ROBOCUP_TEAM_ID: 5
      ROBOCUP_ROBOT_ID: 1
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10021"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1
