version: "3.3"

services:

  simulator:
    extends:
      file: docker-compose.yaml
      service: simulator
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
      - /dev/snd:/dev/snd:rw
      - ./external/webots/projects/samples/contests/robocup/controllers/referee/team_1.json:/root/webots/projects/samples/contests/robocup/controllers/referee/team_1.json:rw
      - ./external/webots/projects/samples/contests/robocup/controllers/referee/team_2.json:/root/webots/projects/samples/contests/robocup/controllers/referee/team_2.json:rw
      - ./external/webots/projects/samples/contests/robocup/protos/:/root/webots/projects/samples/contests/robocup/protos/:rw

  friendly1: # Goalie
    extends:
      file: docker-compose.yaml
      service: friendly
    environment:
      X_POS: 4
      Y_POS: -3.15
      ANGLE: 1.57
      GOALIE: "true"
      ROBOCUP_ROBOT_ID: 1
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "127.0.0.1:10001"
      ROBOT_NAME: robot1
      ROBOCUP_MIRROR_SERVER_IP: 0.0.0.0
      ROBOCUP_GAMECONTROLLER_IP: 0.0.0.0
      TEAM_ID: 16
      ENABLE_PYBULLET: "false"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1

  friendly2: # Left midfield
    extends:
      file: docker-compose.yaml
      service: friendly
    environment:
      X_POS: 1
      Y_POS: -3.15
      ANGLE: 1.57
      GOALIE: "false"
      ROBOT_NAME: "robot2"
      ROBOCUP_ROBOT_ID: 2
      ROBOCUP_TEAM_ID: 16
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "127.0.0.1:10002"
      ROBOCUP_GAMECONTROLLER_IP: "0.0.0.0"
      ROBOCUP_MIRROR_SERVER_IP: "0.0.0.0"
      COMPETITION: "true"
      SINGLE_STRATEGY_SOURCE: "true"
      PYTHONUNBUFFERED: 1

  friendly3: # Striker
    extends:
      file: docker-compose.yaml
      service: friendly
    environment:
      X_POS: 1
      Y_POS: 3.15
      ANGLE: -1.57
      GOALIE: "false"
      ROBOT_NAME: "robot3"
      ROBOCUP_ROBOT_ID: 3
      ROBOCUP_TEAM_ID: 16
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "127.0.0.1:10003"
      ROBOCUP_GAMECONTROLLER_IP: "0.0.0.0"
      ROBOCUP_MIRROR_SERVER_IP: "0.0.0.0"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1
      SINGLE_STRATEGY_SOURCE: "true"

  friendly4: # Right midfield
    extends:
      file: docker-compose.yaml
      service: friendly
    environment:
      X_POS: 4
      Y_POS: 3.15
      ANGLE: -1.57
      GOALIE: "false"
      ROBOT_NAME: "robot4"
      ROBOCUP_ROBOT_ID: 4
      ROBOCUP_TEAM_ID: 16
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "127.0.0.1:10004"
      ROBOCUP_GAMECONTROLLER_IP: "0.0.0.0"
      ROBOCUP_MIRROR_SERVER_IP: "0.0.0.0"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1
      SINGLE_STRATEGY_SOURCE: "true"

  oppponent1: # Goalie
    extends:
      file: docker-compose.yaml
      service: opponent
    environment:
      X_POS: -4
      Y_POS: -3.15
      ANGLE: 1.57
      GOALIE: "true"
      ROBOCUP_TEAM_ID: 25
      ROBOCUP_ROBOT_ID: 1
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10021
      ROBOT_NAME: robot5
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1
      SINGLE_STRATEGY_SOURCE: "true"

  oppponent2: # Left midfield
    extends:
      file: docker-compose.yaml
      service: opponent
    environment:
      X_POS: -1
      Y_POS: -3.15
      ANGLE: 1.57
      ROBOCUP_TEAM_ID: 25
      ROBOCUP_ROBOT_ID: 2
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10022
      ROBOT_NAME: robot6
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1
      SINGLE_STRATEGY_SOURCE: "true"

  oppponent3: # Striker
    extends:
      file: docker-compose.yaml
      service: opponent
    environment:
      X_POS: -1
      Y_POS: 3.15
      ANGLE: -1.57
      ROBOCUP_TEAM_ID: 25
      ROBOCUP_ROBOT_ID: 3
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10023
      ROBOT_NAME: robot7
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1
      SINGLE_STRATEGY_SOURCE: "true"

  oppponent4: # Right midfield
    extends:
      file: docker-compose.yaml
      service: opponent
    environment:
      X_POS: -4
      Y_POS: 3.15
      ANGLE: -1.57
      ROBOCUP_TEAM_ID: 25
      ROBOCUP_ROBOT_ID: 4
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10024
      ROBOT_NAME: robot8
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1
      SINGLE_STRATEGY_SOURCE: "true"

networks:
  friendly:
    name: friendly
  opponent:
    name: opponent
