version: "3.3"

services:

  simulator:
    extends:
      file: docker-compose.yaml
      service: simulator
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
      - /dev/snd:/dev/snd:rw
      - ./external/webots/projects/samples/contests/robocup/controllers/referee/team_1.json:/root/webots/projects/samples/contests/robocup/controllers/referee/team_1.json:rw
      - ./external/webots/projects/samples/contests/robocup/controllers/referee/team_2.json:/root/webots/projects/samples/contests/robocup/controllers/referee/team_2.json:rw
      - ./external/webots/projects/samples/contests/robocup/protos/:/root/webots/projects/samples/contests/robocup/protos/:rw

  friendly1:
    extends:
      file: docker-compose.yaml
      service: friendly
    environment:
      X_POS: 4
      Y_POS: -3.15
      YAW: 1.57
      ROBOCUP_ROBOT_ID: 1
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10001"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      ROBOCUP_TEAM_ID: 16
      ENABLE_PYBULLET: "false"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1

  friendly2: # Left midfield
    extends:
      file: docker-compose.yaml
      service: friendly
    environment:
      X_POS: 1
      Y_POS: -3.15
      YAW: 1.57
      ROBOCUP_ROBOT_ID: 2
      ROBOCUP_TEAM_ID: 16
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10002"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1

  friendly3: # Striker
    extends:
      file: docker-compose.yaml
      service: friendly
    environment:
      X_POS: 1
      Y_POS: 3.15
      YAW: -1.57
      ROBOCUP_ROBOT_ID: 3
      ROBOCUP_TEAM_ID: 16
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10003"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1

  friendly4: # Right midfield
    extends:
      file: docker-compose.yaml
      service: friendly
    environment:
      X_POS: 4
      Y_POS: 3.15
      YAW: -1.57
      ROBOCUP_ROBOT_ID: 4
      ROBOCUP_TEAM_ID: 16
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10004"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1

  oppponent1: # Goalie
    extends:
      file: docker-compose.yaml
      service: opponent
    environment:
      X_POS: -4
      Y_POS: -3.15
      YAW: 1.57
      ROBOCUP_TEAM_ID: 5
      ROBOCUP_ROBOT_ID: 1
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10021"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1

  oppponent2: # Left midfield
    extends:
      file: docker-compose.yaml
      service: opponent
    environment:
      X_POS: -1
      Y_POS: -3.15
      YAW: 1.57
      ROBOCUP_TEAM_ID: 5
      ROBOCUP_ROBOT_ID: 2
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10021"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1

  oppponent3: # Striker
    extends:
      file: docker-compose.yaml
      service: opponent
    environment:
      X_POS: -1
      Y_POS: 3.15
      YAW: -1.57
      ROBOCUP_TEAM_ID: 5
      ROBOCUP_ROBOT_ID: 3
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10023"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1

  oppponent4: # Right midfield
    extends:
      file: docker-compose.yaml
      service: opponent
    environment:
      X_POS: -4
      Y_POS: 3.15
      YAW: -1.57
      ROBOCUP_TEAM_ID: 5
      ROBOCUP_ROBOT_ID: 4
      ROBOCUP_TEAM_COLOR: "blue"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10024"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      COMPETITION: "true"
      PYTHONUNBUFFERED: 1
