update_min_d: 0.05
update_min_a: 0.1
use_map_topic: true
scan_topic: scan
initial_pose_a: 0.0
initial_cov_xx: 1.0
initial_cov_yy: 1.0
odom_frame_id: "odom"
base_frame_id: "base_camera"
global_frame_id: "world"
transform_tolerance: 0.05