min_particles: 100
max_particles: 5000
kld_err: 0.00001
update_min_d: 0.2
update_min_a: 0.01
resample_interval: 2
gui_publish_rate: 1
transform_tolerance: 5
laser_model_type: "likelihood_field_prob"
laser_max_beams: 100

odom_model_type: "omni-corrected"
odom_alpha1: 0.9
odom_alpha2: 0.9
odom_alpha3: 0.9
odom_alpha4: 0.9
odom_alpha5: 0.9

use_map_topic: true
first_map_only: true
scan_topic: scan
initial_cov_xx: 1
initial_cov_yy: 1
initial_cov_aa: 1.57
global_frame_id: "world"
