ROBOCUP_ROBOT_ID: 1
ROBOCUP_TEAM_COLOR: blue
ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10021
ROBOCUP_MIRROR_SERVER_IP: 127.0.0.1
ROBOCUP_GAMECONTROLLER_IP: 127.0.1.1
X_POS: -4
Y_POS: -3.6
ANGLE: 1.57
ROBOT_NAME: robot1
COMPETITION: true
GOALIE: true
TEAM_ID: 16
ENABLE_PYBULLET: false
