name: ros_ci

on:
  pull_request:
    branches: [master]

env:
  GITHUB_WORKSPACE: $HOME/catkin_ws/src/soccerbot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: false
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: soccerbot
          target-ros1-distro: noetic
