name: catkin_lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Install catkin_lint
        run: sudo apt update && sudo apt install catkin-lint

      - name: Run catkin_lint
        run: catkin_lint ${{github.workspace}}
