name: Integration Test

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          df -h
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the Docker image
        run: |
          docker pull utrarobosoccer/soccerbot
          docker buildx build . --file Dockerfile --tag utrarobosoccer/soccerbot --cache-from utrarobosoccer/soccerbot --build-arg BUILDKIT_INLINE_CACHE=1
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Run integration test
        run: |
          python test_integration.py
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: soccerbot/bags/*
          retention-days: 14