name: ROS CI

on:
  pull_request:
    branches: [master]

env:
  GITHUB_WORKSPACE: /home/runner/catkin_ws/src/soccerbot

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          df -h
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Move directory
        run: |
          mkdir -p $HOME/catkin_ws/src/soccerbot
          mv $GITHUB_WORKSPACE/* $HOME/catkin_ws/src/soccerbot
      - name: Install dependencies
        run: |
          cd $HOME/catkin_ws/src/soccerbot
          source /opt/ros/noetic/setup.bash
          rosdep update
          rosdep install --from-path -i -y .
          pip install -r requirements.txt
          sudo apt-get install -y python3-catkin-tools
      - name: Build Soccerbot
        run: |
          cd $HOME/catkin_ws
          source /opt/ros/noetic/setup.bash
          catkin init
          catkin build
          catkin test
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the Docker image
        run: |
          cd $HOME/catkin_ws/src/soccerbot
          docker pull utrarobosoccer/soccerbot
          docker buildx build . --file Dockerfile --tag utrarobosoccer/soccerbot --cache-from utrarobosoccer/soccerbot --build-arg BUILDKIT_INLINE_CACHE=1
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Run integration test
        run: |
          cd $HOME/catkin_ws/src/soccerbot
          python test_integration.py
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: soccerbot/bags/*
          retention-days: 14
