name: ros_ci

on:
  pull_request:
    branches: [master]

env:
  GITHUB_WORKSPACE: /home/runner/catkin_ws/src/soccerbot

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Prepare docker containers
        run: |
          docker-compose pull
          docker-compose up -d
      - name: View Docker-compose logs
        if: always()
        run: |
          docker-compose logs
